db:
  log: true
  timeout: 5 # Query timeout in seconds
  createschema: false
  psn: ${APP_CFG_DB_PSN}

server:
  port: ':8080'
  debug: true
  readtimeout: 10 # Request read timeout in minutes
  writetimeout: 5 # Response write timeout in minutes

jwt:
  realm: jwtrealm # Change this value
  duration: 15
  signingalgorithm: HS256
